### ISSUE TITLE
  .

### ISSUE THREAD

**Issue by ImaneLboukili** [webstah/self-supervised-bss-via-multi-encoder-ae#3]

**Comment by mbwebster** [comment]
I am guessing you figured it out, but just in case, you can see an example of source inference for the triangles and circles experiment here: [main/notebooks/triangles_and_circles_model_test.ipynb](https://github.com/webstah/self-supervised-bss-via-multi-encoder-ae/blob/main/notebooks/triangles_and_circles_model_test.ipynb)
